default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_APP'] || 'my_collection_development' %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB_TEST'] || 'my_collection_test' %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB_APP'] || 'my_collection_production' %>
  pool: 50

